EbooksPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('papers/', include(('papers.urls', 'papers'), namespace='papers')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('base.api.urls')),
    path('api/', include('books.api.urls')),
    path('api/', include('papers.api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = 'base.errors.error403'
handler404 = 'base.errors.error404'
handler500 = 'base.errors.error500'

base/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('users/all', UserViewset, basename='Users')
router.register('users/staff', StaffViewset, basename='Staff Members')
router.register('users/active', ActiveUsersViewset, basename='Active Users')
router.register('users/end', EndUsersViewset, basename='End Users')
router.register('profiles', EndUsersViewset, basename='Profiles')
router.register('tags', TagsViewset, basename='Tags')
router.register('sections', SectionsViewset, basename='Sections')

urlpatterns = [
    path('', include(router.urls)),
    path('count', AllCountsViewset.as_view(), name='All Counts'),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.home, name='home'),
    path('contact', views.contact, name='contact'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('change/', views.change, name='change'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import *
from django.dispatch import receiver
from django.db.models.signals import post_save

from books.models import *
from papers.models import *

from simple_history.models import HistoricalRecords
from ConsoleMessenger import ConsoleMessage

global CMD
CMD = ConsoleMessage()

# Create your models here.
SECTION_CATEGORY = [
    ('books', 'Books'),
    ('papers', 'Papers'),
    ('both', 'Books & Papers')
]

USER_THEME = [
    ('light', 'Light'),
    ('dark', 'Dark')
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    theme = models.CharField(max_length=20, choices=USER_THEME, default='light')
    history = HistoricalRecords()

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'ep_profile'
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'ep_tag'
        verbose_name = 'tag'
        verbose_name_plural = 'tags'
        ordering = ('name',)

class Section(models.Model):
    name = models.CharField(max_length=50, unique=True)
    books = models.ManyToManyField(Book, blank=True)
    papers = models.ManyToManyField(Paper, blank=True)
    category = models.CharField(max_length=20, choices=SECTION_CATEGORY, default='books')
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'ep_section'
        verbose_name = 'section'
        verbose_name_plural = 'sections'
        ordering = ('name',)

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    try:
        if created:
            Profile.objects.create(user=instance).save()
    except Exception as err:
        CMD.danger(err)

base/forms.py
from django import forms
from django.forms import TextInput, Textarea

from allauth.account.forms import SignupForm
from captcha.fields import ReCaptchaField

class ContactForm(forms.Form):
    firstname = forms.CharField(max_length=15, widget=TextInput())
    lastname = forms.CharField(max_length=15, widget=TextInput())
    email = forms.EmailField(widget=TextInput())
    subject = forms.CharField(max_length=50, widget=TextInput())
    message = forms.CharField(max_length=500, widget=Textarea())

class CustomSignUpForm(SignupForm):
    first_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Firstname',}))
    last_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Lastname',}))
    captcha = ReCaptchaField()

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

class ProfileForm(forms.Form):
    firstname = forms.CharField(max_length=15, widget=TextInput())
    lastname = forms.CharField(max_length=15, widget=TextInput())
    email = forms.EmailField(widget=TextInput())
    username = forms.CharField(max_length=15, widget=TextInput())

base/api/views.py
from .serializers import *
from .filtersets import *
from books.models import *
from papers.models import *
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import AllowAny
from rest_framework.views import APIView
from rest_framework.response import Response

# Create your views here.
class UserViewset(ModelViewSet):
    serializer_class = UsersSerializer
    filterset_class = UserFilter
    queryset = User.objects.all()

class StaffViewset(ModelViewSet):
    serializer_class = StaffSerializer
    filterset_class = StaffFilter
    
    def get_queryset(self):
        queryset = User.objects.filter(is_staff=True)
        return queryset
    
class ActiveUsersViewset(ModelViewSet):
    serializer_class = ActiveUsersSerializer
    filterset_class = ActiveUsersFilter

    def get_queryset(self):
        queryset = User.objects.filter(is_active=True)
        return queryset

class EndUsersViewset(ModelViewSet):
    serializer_class = EndUsersSerializer
    filterset_class = EndUsersFilter

    def get_queryset(self):
        queryset = User.objects.filter(is_staff=False)
        return queryset

class ProfilesViewset(ModelViewSet):
    serializer_class = ProfilesSerializer
    filterset_class = ProfilesFilter
    queryset = Profile.objects.all()

class TagsViewset(ModelViewSet):
    serializer_class = TagsSerializer
    filterset_class = TagsFilter
    queryset = Tag.objects.all()

class SectionsViewset(ModelViewSet):
    serializer_class = SectionsSerializer
    filterset_class = SectionsFilter
    queryset = Section.objects.all()

class AllCountsViewset(APIView):
    permission_classes = [AllowAny]

    def get(self, request, format=None):
        users = User.objects.all().count()
        books = Book.objects.all().count()
        papers = Paper.objects.all().count()
        book_downloads = sum([book.downloads for book in Book.objects.all()])
        paper_downloads = sum([paper.downloads for paper in Paper.objects.all()])
        total_downloads = book_downloads + paper_downloads

        return Response(
            {
                'users': users,
                'books': books,
                'papers': papers,
                'book_downloads': book_downloads,
                'paper_downloads': paper_downloads,
                'total_downloads': total_downloads
            }
        )

base/views.py
from django.conf import settings
from django.template import loader
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

import os, requests

from .forms import *
from .models import *

# Create your views here.
def home( request ):
    nav_actives = [None for i in range(7)]
    nav_actives[0] = 'active'

    book_downloads = sum([book.downloads for book in Book.objects.all()])
    paper_downloads = sum([paper.downloads for paper in Paper.objects.all()])
    total_downloads = book_downloads+paper_downloads
    sections = Section.objects.all()
    form = ContactForm()

    Context = {
        'form': form,
        'nav_actives': nav_actives,
        'sections': sections,
        'book_downloads': book_downloads,
        'total_downloads': total_downloads,
        'paper_downloads': paper_downloads,
    }
    t = loader.get_template('base/home.html')
    return HttpResponse(t.render(Context, request))

def contact( request ):
    form = ContactForm()
    nav_actives = [None for i in range(7)]
    nav_actives[2] = 'active'

    if request.method == "POST":
       firstname = request.POST['firstname']
       lastname = request.POST['lastname']
       email = request.POST['email']
       subject = request.POST['subject']
       message = request.POST['message']

       mail_message = f"""
           Name : {firstname} {lastname}
           Email Address : {email}
           Message : {message}
       """

       try:
           send_mail(
               subject,
               mail_message,
               settings.EMAIL_HOST_USER,
               settings.TO,
               fail_silently=False,
           )
           messages.success(request, 'Message sent successfully!')
       except Exception as e:
           print(e)
           messages.warning(request, 'Please check you internet connection!')

       Context = {
           'form': form,
           'nav_actives': nav_actives,
           'firstname': firstname,
           'lastname': lastname,
           'email': email,
           'subject': subject,
           'message': message,
       }
    else:
        Context = {
            'form': form,
            'nav_actives': nav_actives,
        }

    t = loader.get_template('base/contact.html')
    return HttpResponse(t.render(Context, request))


def profile(request):
    form = ProfileForm()
    user = request.user

    first_name = user.first_name
    last_name = user.last_name
    email = user.email
    username = user.username

    nav_actives = [None for i in range(7)]
    nav_actives[5] = 'active'

    if request.method == "POST":
       first_name = request.POST['firstname']
       last_name = request.POST['lastname']
       email = request.POST['email']
       username = request.POST['username']

       update = True

       if not first_name.isalpha():
          messages.warning(request, 'Invalid firstname!')
          update = False

       if not last_name.isalpha():
          messages.warning(request, 'Invalid lastname!')
          update = False

       if not username.isalnum() and username.isdigit():
          messages.warning(request, 'Invalid username!')
          update = False

       if User.objects.filter(username=username).exists() and user.username != username:
          messages.warning(request, 'Username is already taken!')
          update = False

       if User.objects.filter(email=email).exists() and user.email != email:
          messages.warning(request, 'Email is already registered!')
          update = False

       try:
           if update:
              user.first_name = first_name
              user.last_name = last_name
              user.email = email
              user.username = username
              user.save()

              messages.success(request, 'Your profile has been updated!')
       except Exception as e:
           print(e)
           messages.warning(request, 'Invalid Information!')

    Context ={
        'form': form,
        'nav_actives': nav_actives,
        'first_name': first_name,
        'last_name': last_name,
        'email': email,
        'username': username,
    }
    t = loader.get_template('base/profile.html')

    return HttpResponse(t.render(Context, request))

def about(request):
    t = loader.get_template('base/about.html')
    Context = {}
    return HttpResponse(t.render(Context, request))

def change(request):
    theme = request.GET.get('theme', False)
    if theme:
        profile = Profile.objects.get(user=request.user)
        profile.theme = theme
        profile.save()
    return redirect('/profile')

templates/base/about.html
{% extends 'base/base.html' %}
{% load static %}

{% block links %}
{% if user.is_authenticated %}
    {% if user.user_profile.theme == 'dark' %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/base/about_dark.css' %}">
    {% endif %}
{% endif %}
{% endblock %}

templates/base/contact.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Contact | EbooksPortal
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static '/css/base/contact.css' %}">

{% if user.is_authenticated %}
    {% if user.user_profile.theme == 'dark' %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/base/contact_dark.css' %}">
    {% endif %}
{% endif %}
{% endblock %}

{% block content %}
<section class="contact bg-light" id="contact">

    <h1 class="text-center">
        Contact Us
    </h1>

    <div class="container justify-content-center">

        <form name="frm" action="{% url 'base:contact' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">

                <div class="form-row">
                    <div class="col">
                        <label for="id_firstname" data-text="{{ firstname }}">
                            Firstname
                        </label>
                        {% render_field form.firstname class="form-control" auto-complete="off" %}
                    </div>
                    <div class="col">
                        <label for="id_lastname" data-text="{{ lastname }}">
                            Lastname
                        </label>
                        {% render_field form.lastname class="form-control" auto-complete="off" %}
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label for="id_email" data-text="{{ email }}">
                            Email
                        </label>
                        {% render_field form.email class="form-control" auto-complete="off" %}
                    </div>
                    <div class="col">
                        <label for="id_subject" data-text="{{ subject }}">
                            Subject
                        </label>
                        {% render_field form.subject class="form-control" auto-complete="off" %}
                    </div>
                </div>

                <label for="id_message" data-text="{{ message }}">
                    Message
                </label>
                {% render_field form.message class="form-control" auto-complete="off" %}

                <button type="submit" class="btn btn-dark">
                    Submit
                </button>

            </div>
        </form>

    </div>
</section>
{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="{% static '/js/base/contact.js' %}"></script>
{% endblock %}

templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% load books_filter %}
{% load widget_tweaks %}

{% block title %}
    EbooksPortal
{% endblock %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/base/index.css' %}">

{% if user.is_authenticated %}
    {% if user.user_profile.theme == 'dark' %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/base/home_dark.css' %}">
    {% endif %}
{% endif %}

{% endblock %}

{% block content %}
    <main role="main">
            
        <section class="jumbotron text-center">
            <div class="container">
                <h1>
                    EbooksPortal
                </h1>
                <p class="lead text-muted">
                    A hub for free ebooks for computer science.
                </p>
                <p>
                    <a href="{% url 'books:all' %}" class="btn btn-info my-2">
                        explore more
                    </a>
                </p>
            </div>
        </section>

        {% for section in sections %}
        <div class="album py-5 bg-light">
            <h1 class="galada text-center">
                {{ section.name }}
            </h1>

            <div class="container">
                <div class="row">
                    
                    {% if section.books %}
                        {% for book in section.books.all %}
                            <div class="col-md-4">
                                <div class="card mb-4 shadow-sm">
                                    <img src="{{ book.image|lnk_filter }}" class="card-img-top">

                                    <div class="card-body">
                                        <p class="lead text-center">
                                            {{ book.title }}
                                        </p>

                                        <p class="lead">
                                            {% for tag in book.tags.all %}
                                            <a href="{% url 'books:books' %}?query={{tag.name}}" class="badge badge-secondary">
                                                {{ tag.name }}
                                            </a>
                                            {% endfor %}
                                        </p>

                                        <div class="d-flex justify-content-between align-items-center">

                                            <div class="btn-group">
                                                {% if user.is_authenticated %}
                                                    <button onclick="mark_download('{% url 'books:download' book.id %}', '{{ book.attachment|lnk_filter }}')" class="btn btn-sm btn-outline-secondary">
                                                        Download
                                                    </button>
                                                {% else %}
                                                    <a href="{% url 'account_login' %}" class="btn btn-sm btn-outline-secondary">
                                                        Download
                                                    </a>
                                                {% endif %}
                                                <div onclick="copythis(window.location.protocol+'\\'+window.location.hostname+'{% url 'books:open_portal' book.id %}')" class="btn btn-sm btn-outline-secondary copybtn">
                                                    Copy Link
                                                </div>
                                            </div>

                                            <small class="text-muted">
                                                <i class="fa fa-cloud-download"></i>
                                                {{ book.downloads }}
                                            </small>

                                            <small class="text-muted">
                                                {{ book.create_date }}
                                            </small>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    
                    {% if section.papers %}
                        {% for paper in section.papers.all %}
                            <div class="col-md-4">
                                <div class="card mb-4 shadow-sm">
                                    <img src="{{ paper.image|lnk_filter }}" class="card-img-top">

                                    <div class="card-body">
                                        <p class="lead text-center">
                                            {{ paper.title }}
                                        </p>

                                        <p class="lead">
                                            {% for tag in paper.tags.all %}
                                            <a href="{% url 'papers:query' tag.name %}" class="badge badge-secondary">
                                                {{ tag.name }}
                                            </a>
                                            {% endfor %}
                                        </p>

                                        <div class="d-flex justify-content-between align-items-center">

                                            <div class="btn-group">
                                                {% if user.is_authenticated %}
                                                    <button onclick="mark_download('{% url 'papers:download' paper.id %}', '{{ paper.attachment|lnk_filter }}')" class="btn btn-sm btn-outline-secondary">
                                                        Download
                                                    </button>
                                                {% else %}
                                                    <a href="{% url 'accounts_login' %}" class="btn btn-sm btn-outline-secondary">
                                                        Download
                                                    </a>
                                                {% endif %}
                                                <div onclick="copythis(window.location.protocol+String.fromCharCode(47, 47)+window.location.hostname+'{% url 'papers:open_portal' paper.id %}')" class="btn btn-sm btn-outline-secondary copybtn">
                                                    Copy Link
                                                </div>
                                            </div>

                                            <small class="text-muted">
                                                <i class="fa fa-cloud-download"></i>
                                                {{ paper.downloads }}
                                            </small>

                                            <small class="text-muted">
                                                {{ paper.create_date }}
                                            </small>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}

                </div>
            </div>
        </div>
        {% endfor %}

    </main>

    <section class="counter">

            <div class="crcl bg-dark">
                <div>
                    Book Downloads
                </div>
                <p class="count">
                    {{ book_downloads }}
                </p>
            </div>
            <div class="crcl bg-dark">
                <div>
                    Total Downloads
                </div>
                <p class="count">
                    {{ total_downloads }}
                </p>
            </div>
            <div class="crcl bg-dark">
                <div>
                    Paper Downloads
                </div>
                <p class="count">
                    {{ paper_downloads }}
                </p>
            </div>

    </section>

    <section class="contact" id="contact">

        <h1 class="text-center">
            Contact Us
        </h1>

        <div class="container justify-content-center">

            <form action="{% url 'base:contact' %}" method="POST">
                <div class="form-group">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="col">
                            <label for="id_firstname">
                                Firstname
                            </label>
                            {% render_field form.firstname class="form-control" auto-complete="off" %}
                        </div>
                        <div class="col">
                            <label for="id_lastname">
                                Lastname
                            </label>
                            {% render_field form.lastname class="form-control" auto-complete="off" %}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col">
                            <label for="id_email">
                                Email
                            </label>
                            {% render_field form.email class="form-control" auto-complete="off" %}
                        </div>
                        <div class="col">
                            <label for="id_subject">
                                Subject
                            </label>
                            {% render_field form.subject class="form-control" auto-complete="off" %}
                        </div>
                    </div>

                    <label for="id_message">
                        Message
                    </label>
                    {% render_field form.message class="form-control" auto-complete="off" %}

                    <button type="submit" class="btn btn-dark">
                        Submit
                    </button>

                </div>
            </form>

        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.counterup/1.0/jquery.counterup.min.js"></script>
    <script src="{% static '/js/base/copy_lnk.js' %}"></script>
    <script src="{% static '/js/base/download.js' %}"></script>
    <script src="{% static '/js/base/counter.js' %}"></script>
{% endblock %}

templates/base/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    {{ user.username }} | EbooksPortal
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static '/css/base/profile.css' %}">

{% if user.is_authenticated %}
    {% if user.user_profile.theme == 'dark' %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/base/profile_dark.css' %}">
    {% endif %}
{% endif %}

{% endblock %}

{% block content %}
<section class="profile bg-light" id="profile">

    <h1 class="text-center">
        My Profile
    </h1>

    <div class="container justify-content-center">

        <form name="frm" action="{% url 'base:profile' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">

                <div class="form-row">
                    <div class="col">
                        <label for="id_firstname" data-text="{{ first_name }}">
                            Firstname
                        </label>
                        {% render_field form.firstname class="form-control" auto-complete="off" %}
                    </div>
                    <div class="col">
                        <label for="id_lastname" data-text="{{ last_name }}">
                            Lastname
                        </label>
                        {% render_field form.lastname class="form-control" auto-complete="off" %}
                    </div>
                </div>

                <label for="id_email" data-text="{{ email }}">
                    Email
                </label>
                {% render_field form.email class="form-control" auto-complete="off" %}

                <label for="id_subject" data-text="{{ username }}">
                    Username
                </label>
                {% render_field form.username class="form-control" auto-complete="off" %}

                <label for="theme">Select Theme</label>
                <select name="theme" class="form-control" onchange="location.href = '{% url 'base:change' %}?theme='+this.value;">

                    {% if user.user_profile.theme == 'light' %}
                        <option value="light" selected>Light</option>
                    {% else %}
                        <option value="light">Light</option>
                    {% endif %}
                    
                    {% if user.user_profile.theme == 'dark' %}
                        <option value="dark" selected>Dark</option>
                    {% else %}
                        <option value="dark">Dark</option>
                    {% endif %}

                </select>
                <br>

                <button type="submit" class="btn btn-dark">
                    Submit
                </button>

            </div>
        </form>

    </div>
</section>
{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="{% static '/js/base/profile.js' %}"></script>
{% endblock %}