EbooksPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('papers/', include(('papers.urls', 'papers'), namespace='papers')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('base.api.urls')),
    path('api/', include('books.api.urls')),
    path('api/', include('papers.api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = 'base.errors.error403'
handler404 = 'base.errors.error404'
handler500 = 'base.errors.error500'

base/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('users/all', UserViewset, basename='Users')
router.register('users/staff', StaffViewset, basename='Staff Members')
router.register('users/active', ActiveUsersViewset, basename='Active Users')
router.register('users/end', EndUsersViewset, basename='End Users')
router.register('profiles', EndUsersViewset, basename='Profiles')
router.register('tags', TagsViewset, basename='Tags')
router.register('sections', SectionsViewset, basename='Sections')

urlpatterns = [
    path('', include(router.urls)),
    path('count', AllCountsViewset.as_view(), name='All Counts'),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.home, name='home'),
    path('contact', views.contact, name='contact'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('change/', views.change, name='change'),
]

papers/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('papers/all', PapersViewset, basename='Papers')

urlpatterns = [
    path('', include(router.urls)),
]

papers/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.papers, name='papers'),
    path('all/', views.all, name='all'),
    path('open-portal/<int:paper>/', views.open_portal, name='open_portal'),
    path('download/<int:paper>/', views.download, name='download'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import *
from django.dispatch import receiver
from django.db.models.signals import post_save

from books.models import *
from papers.models import *

from simple_history.models import HistoricalRecords
from ConsoleMessenger import ConsoleMessage

global CMD
CMD = ConsoleMessage()

# Create your models here.
SECTION_CATEGORY = [
    ('books', 'Books'),
    ('papers', 'Papers'),
    ('both', 'Books & Papers')
]

USER_THEME = [
    ('light', 'Light'),
    ('dark', 'Dark')
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    theme = models.CharField(max_length=20, choices=USER_THEME, default='light')
    history = HistoricalRecords()

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'ep_profile'
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'ep_tag'
        verbose_name = 'tag'
        verbose_name_plural = 'tags'
        ordering = ('name',)

class Section(models.Model):
    name = models.CharField(max_length=50, unique=True)
    books = models.ManyToManyField(Book, blank=True)
    papers = models.ManyToManyField(Paper, blank=True)
    category = models.CharField(max_length=20, choices=SECTION_CATEGORY, default='books')
    history = HistoricalRecords()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'ep_section'
        verbose_name = 'section'
        verbose_name_plural = 'sections'
        ordering = ('name',)

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    try:
        if created:
            Profile.objects.create(user=instance).save()
    except Exception as err:
        CMD.danger(err)

papers/models.py
from django.db import models
from django.db.models import CharField
from django.db.models.functions import Lower

from simple_history.models import HistoricalRecords

# Create your models here.
CharField.register_lookup(Lower)

class Paper(models.Model):
    title = models.CharField(max_length=500)
    attachment = models.URLField(max_length=200)
    image = models.URLField(
        max_length=200,
        default='https://github.com/Ajay2810-hub/Ebooks/raw/master/default/images/image_unavailable.jpg'
    )
    tags = models.ManyToManyField(
        'base.Tag', blank=True
    )
    create_date = models.DateField(auto_now_add=True)
    downloads = models.BigIntegerField(default=0)
    history = HistoricalRecords()

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'ep_paper'
        verbose_name = 'paper'
        verbose_name_plural = 'papers'
        ordering = ('-downloads',)

base/forms.py
from django import forms
from django.forms import TextInput, Textarea

from allauth.account.forms import SignupForm
from captcha.fields import ReCaptchaField

class ContactForm(forms.Form):
    firstname = forms.CharField(max_length=15, widget=TextInput())
    lastname = forms.CharField(max_length=15, widget=TextInput())
    email = forms.EmailField(widget=TextInput())
    subject = forms.CharField(max_length=50, widget=TextInput())
    message = forms.CharField(max_length=500, widget=Textarea())

class CustomSignUpForm(SignupForm):
    first_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Firstname',}))
    last_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Lastname',}))
    captcha = ReCaptchaField()

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

class ProfileForm(forms.Form):
    firstname = forms.CharField(max_length=15, widget=TextInput())
    lastname = forms.CharField(max_length=15, widget=TextInput())
    email = forms.EmailField(widget=TextInput())
    username = forms.CharField(max_length=15, widget=TextInput())

base/api/views.py
from .serializers import *
from .filtersets import *
from books.models import *
from papers.models import *
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import AllowAny
from rest_framework.views import APIView
from rest_framework.response import Response

# Create your views here.
class UserViewset(ModelViewSet):
    serializer_class = UsersSerializer
    filterset_class = UserFilter
    queryset = User.objects.all()

class StaffViewset(ModelViewSet):
    serializer_class = StaffSerializer
    filterset_class = StaffFilter
    
    def get_queryset(self):
        queryset = User.objects.filter(is_staff=True)
        return queryset
    
class ActiveUsersViewset(ModelViewSet):
    serializer_class = ActiveUsersSerializer
    filterset_class = ActiveUsersFilter

    def get_queryset(self):
        queryset = User.objects.filter(is_active=True)
        return queryset

class EndUsersViewset(ModelViewSet):
    serializer_class = EndUsersSerializer
    filterset_class = EndUsersFilter

    def get_queryset(self):
        queryset = User.objects.filter(is_staff=False)
        return queryset

class ProfilesViewset(ModelViewSet):
    serializer_class = ProfilesSerializer
    filterset_class = ProfilesFilter
    queryset = Profile.objects.all()

class TagsViewset(ModelViewSet):
    serializer_class = TagsSerializer
    filterset_class = TagsFilter
    queryset = Tag.objects.all()

class SectionsViewset(ModelViewSet):
    serializer_class = SectionsSerializer
    filterset_class = SectionsFilter
    queryset = Section.objects.all()

class AllCountsViewset(APIView):
    permission_classes = [AllowAny]

    def get(self, request, format=None):
        users = User.objects.all().count()
        books = Book.objects.all().count()
        papers = Paper.objects.all().count()
        book_downloads = sum([book.downloads for book in Book.objects.all()])
        paper_downloads = sum([paper.downloads for paper in Paper.objects.all()])
        total_downloads = book_downloads + paper_downloads

        return Response(
            {
                'users': users,
                'books': books,
                'papers': papers,
                'book_downloads': book_downloads,
                'paper_downloads': paper_downloads,
                'total_downloads': total_downloads
            }
        )

base/views.py
from django.conf import settings
from django.template import loader
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

import os, requests

from .forms import *
from .models import *

# Create your views here.
def home( request ):
    nav_actives = [None for i in range(7)]
    nav_actives[0] = 'active'

    book_downloads = sum([book.downloads for book in Book.objects.all()])
    paper_downloads = sum([paper.downloads for paper in Paper.objects.all()])
    total_downloads = book_downloads+paper_downloads
    sections = Section.objects.all()
    form = ContactForm()

    Context = {
        'form': form,
        'nav_actives': nav_actives,
        'sections': sections,
        'book_downloads': book_downloads,
        'total_downloads': total_downloads,
        'paper_downloads': paper_downloads,
    }
    t = loader.get_template('base/home.html')
    return HttpResponse(t.render(Context, request))

def contact( request ):
    form = ContactForm()
    nav_actives = [None for i in range(7)]
    nav_actives[2] = 'active'

    if request.method == "POST":
       firstname = request.POST['firstname']
       lastname = request.POST['lastname']
       email = request.POST['email']
       subject = request.POST['subject']
       message = request.POST['message']

       mail_message = f"""
           Name : {firstname} {lastname}
           Email Address : {email}
           Message : {message}
       """

       try:
           send_mail(
               subject,
               mail_message,
               settings.EMAIL_HOST_USER,
               settings.TO,
               fail_silently=False,
           )
           messages.success(request, 'Message sent successfully!')
       except Exception as e:
           print(e)
           messages.warning(request, 'Please check you internet connection!')

       Context = {
           'form': form,
           'nav_actives': nav_actives,
           'firstname': firstname,
           'lastname': lastname,
           'email': email,
           'subject': subject,
           'message': message,
       }
    else:
        Context = {
            'form': form,
            'nav_actives': nav_actives,
        }

    t = loader.get_template('base/contact.html')
    return HttpResponse(t.render(Context, request))


def profile(request):
    form = ProfileForm()
    user = request.user

    first_name = user.first_name
    last_name = user.last_name
    email = user.email
    username = user.username

    nav_actives = [None for i in range(7)]
    nav_actives[5] = 'active'

    if request.method == "POST":
       first_name = request.POST['firstname']
       last_name = request.POST['lastname']
       email = request.POST['email']
       username = request.POST['username']

       update = True

       if not first_name.isalpha():
          messages.warning(request, 'Invalid firstname!')
          update = False

       if not last_name.isalpha():
          messages.warning(request, 'Invalid lastname!')
          update = False

       if not username.isalnum() and username.isdigit():
          messages.warning(request, 'Invalid username!')
          update = False

       if User.objects.filter(username=username).exists() and user.username != username:
          messages.warning(request, 'Username is already taken!')
          update = False

       if User.objects.filter(email=email).exists() and user.email != email:
          messages.warning(request, 'Email is already registered!')
          update = False

       try:
           if update:
              user.first_name = first_name
              user.last_name = last_name
              user.email = email
              user.username = username
              user.save()

              messages.success(request, 'Your profile has been updated!')
       except Exception as e:
           print(e)
           messages.warning(request, 'Invalid Information!')

    Context ={
        'form': form,
        'nav_actives': nav_actives,
        'first_name': first_name,
        'last_name': last_name,
        'email': email,
        'username': username,
    }
    t = loader.get_template('base/profile.html')

    return HttpResponse(t.render(Context, request))

def about(request):
    t = loader.get_template('base/about.html')
    Context = {}
    return HttpResponse(t.render(Context, request))

def change(request):
    theme = request.GET.get('theme', False)
    if theme:
        profile = Profile.objects.get(user=request.user)
        profile.theme = theme
        profile.save()
    return redirect('/profile')

papers/api/views.py
from .serializers import *
from .filtersets import *
from papers.models import *
from rest_framework.viewsets import ModelViewSet

class PapersViewset(ModelViewSet):
    serializer_class = PapersSerializer
    filterset_class = PapersFilter
    queryset = Paper.objects.all()

papers/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.template import loader
from .models import *
import requests
from django.core.paginator import Paginator

# Create your views here.
def papers(request, query):
    nav_actives = [None for i in range(7)]
    text = request.GET.get('query', False)

    if text:
       query = text.strip().lower()
       qlookup1 = Q(tags__name__lower=query)
       qlookup2 = Q(title__lower__contains=query)
       papers = Paper.objects.filter(qlookup1 | qlookup2).distinct().order_by('create_date')

       offset = int(request.GET.get('offset', 10))
       page_number = request.GET.get('page', 1)
       page = Paginator(papers, per_page=offset).get_page(page_number)

       Context = {
           'nav_actives': nav_actives,
           'papers': page.object_list,
           'page': page,
           'query': text,
           'offset': offset,
           'limits': [10, 25, 50, 100]
       }       
       t = loader.get_template('papers/query_papers.html')
       return HttpResponse(t.render(Context, request))
    else:
       return redirect('/papers/all')

def all(request):
    nav_actives = [None for i in range(7)]
    nav_actives[4] = 'active'

    papers = Paper.objects.all().order_by('create_date')
    offset = int(request.GET.get('offset', 10))
    page_number = request.GET.get('page', 1)
    page = Paginator(papers, per_page=offset).get_page(page_number)

    Context = {
        'nav_actives': nav_actives,
        'papers': page.object_list,
        'page': page,
        'offset': offset,
        'limits': [10, 25, 50, 100]
    }
    t = loader.get_template('papers/all_papers.html')
    return HttpResponse(t.render(Context, request))

def open_portal(request, paper):
    paper = Paper.objects.filter(id=paper)
    if paper.exists():
        Context = { 'paper': paper.first() }
        t = loader.get_template('papers/open_portal.html')
        return HttpResponse(t.render(Context, request))
    else:
       raise Http404('Paper id not provided!')

def download(request, paper):
    try:
        if paper:
            paper = paper.objects.get(id=paper)
            paper.downloads += 1
            paper.save()
            return JsonResponse({'ans': True})
        return JsonResponse({'ans': False})
    except Exception as e:
        print('Error incrementing book download')
        print(e)
        return JsonResponse({'ans': False})

templates/papers/all_papers.html
{% extends 'papers/base.html' %}
{% load static %}
{% load papers_filter %}

{% block title %}
    Papers | EbooksPortal
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static '/css/papers/all_papers.css' %}">
{% endblock %}

{% block content %}

    <br>

    <div class="container">
        <form action="{% url 'papers:papers' %}" method="GET">
            <div class="input-group">
                <input type="search" name="query" id="search" placeholder="search" class="form-control" value="{{ query }}" required>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-dark">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>

    {% if papers %}
    <br>
    <div class="container">
        <div class="offset">
            <label for="offset" class="lead">papers per page :</label>
            <select name="offset" id="offset" class="form-control" onchange="location.href = '?offset='+this.value;">
                {% for limit in limits %}
                    {% if limit == offset %}
                    <option value="{{limit}}" selected>{{limit}}</option>
                    {% else %}
                    <option value="{{limit}}">{{limit}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
    </div>
    {% endif %}

    <div class="album py-5 bg-light">

        <div class="container">
            <div class="row">
                
                {% for paper in papers %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img src="{{ paper.image|lnk_filter }}" class="card-img-top">

                        <div class="card-body">
                            <p class="lead text-center">
                                {{ paper.title }}
                            </p>

                            <p class="lead">
                                {% for tag in paper.tags.all %}
                                <a href="{% url 'papers:papers' %}?query={{tag.name}}" class="badge badge-secondary">
                                    {{ tag.name }}
                                </a>
                                {% endfor %}
                            </p>

                            <div class="d-flex justify-content-between align-items-center">

                                <div class="btn-group">
                                    {% if user.is_authenticated %}
                                        <button onclick="mark_download('{% url 'papers:download' paper.id %}', '{{ paper.attachment|lnk_filter }}')" class="btn btn-sm btn-outline-secondary">
                                            Download
                                        </button>
                                    {% else %}
                                        <a href="{% url 'accounts_login' %}" class="btn btn-sm btn-outline-secondary">
                                            Download
                                        </a>
                                    {% endif %}
                                    <div onclick="copythis(window.location.protocol+'\\'+window.location.hostname+'{% url 'papers:open_portal' paper.id %}')" class="btn btn-sm btn-outline-secondary copybtn">
                                        Copy Link
                                    </div>
                                </div>

                                <small class="text-muted">
                                    <i class="fa fa-cloud-download"></i>
                                    {{ paper.downloads }}
                                </small>

                                <small class="text-muted">
                                    {{ paper.create_date }}
                                </small>

                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>


    {% if page %}
        <div class="container-fluid">
            <ul class="pagination justify-content-center">

                {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?offset={{offset}}&page=1" title="1">
                            &laquo; first
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?offset={{offset}}&page={{ page.previous_page_number }}" title="{{ page.previous_page_number }}">
                            prev
                        </a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="?offset={{offset}}&page={{ page.number }}" title="{{ page.number }}">
                        {{ page.number }}
                    </a>
                </li>

                {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?offset={{offset}}&page={{ page.next_page_number }}" title="{{ page.next_page_number }}">
                            next
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?offset={{offset}}&page={{ page.paginator.num_pages }}" title="{{ page.paginator.num_pages }}">
                            last &raquo;
                        </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    {% endif %}


{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static '/js/base/copy_lnk.js' %}"></script>
    <script src="{% static '/js/base/download.js' %}"></script>
{% endblock %}

templates/papers/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" href="https://dl.dropboxusercontent.com/s/k72xssh7yys6sbo/logo.png?dl=0" type="png/image" sizes="16x16">

	<title> {% block title %}{% endblock %} </title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/papers/base.css' %}">

    {% block links %}
	{% endblock %}
	
	{% if user.is_authenticated %}
		{% if user.user_profile.theme == 'dark' %}
			<link rel="stylesheet" type="text/css" href="{% static '/css/papers/dark.css' %}">
		{% endif %}
	{% endif %}

</head>
<body>
	
	<div class="nav-container bg-dark">
		<div class="container">
			<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
				
				<a href="{% url 'base:home' %}" class="navbar-brand d-flex align-items-center">
					EbooksPortal
				</a>

				<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="nav">

					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a href="{% url 'base:home' %}" class="nav-link">
								<span class="{{ nav_actives.0 }}">
									<i class="fa fa-home"></i> Home
								</span>
							</a>
						</li>
						<li class="nav-item active">
							<a href="{% url 'base:about' %}" class="nav-link">
								<span class="{{ nav_actives.1 }}">
									<i class="fa fa-info-circle"></i> About
								</span>
							</a>
						</li>
						<li class="nav-item active">
							{% if nav_actives.2 %}
							<a href="{% url 'base:contact' %}" class="nav-link">
								<span class="active">
									<i class="fa fa-phone-alt"></i> Contact
								</span>
							</a>
							{% else %}
							<a href="{% url 'base:contact' %}" class="nav-link">
								<span>
									<i class="fa fa-phone-alt"></i> Contact
								</span>
							</a>
							{% endif %}
						</li>
						<li class="nav-item active">
							{% if nav_actives.3 %}
							<a href="{% url 'books:all' %}" class="nav-link">
								<span class="active">
									<i class="fa fa-book"></i> Books
								</span>
							</a>
							{% else %}
							<a href="{% url 'books:all' %}" class="nav-link">
								<span>
									<i class="fa fa-book"></i> Books
								</span>
							</a>
							{% endif %}
						</li>
						<li class="nav-item active">
							{% if nav_actives.4 %}
							<a href="{% url 'papers:all' %}" class="nav-link">
								<span class="active">
									<i class="fa fa-sticky-note"></i> Papers
								</span>
							</a>
							{% else %}
							<a href="{% url 'papers:all' %}" class="nav-link">
								<span>
									<i class="fa fa-sticky-note"></i> Papers
								</span>
							</a>
							{% endif %}
						</li>
						
						{% if user.is_authenticated %}
						{% if user.is_staff %}
						<li class="nav-item active">
							<a href="/admin" class="nav-link">
								<span>
									<i class="fa fa-user-cog"></i> Admin Panel
								</span>
							</a>
						</li>
						{% endif %}
						<li class="nav-item active">
							{% if nav_actives.5 %}
							<a href="{% url 'base:profile' %}" class="nav-link">
								<span class="active">
									<i class="fa fa-user"></i> {{ user.username }}
								</span>
							</a>
							{% else %}
							<a href="{% url 'base:profile' %}" class="nav-link">
								<span>
									<i class="fa fa-user"></i> {{ user.username }}
								</span>
							</a>
							{% endif %}
						</li>
						<li class="nav-item active">
							<a href="{% url 'account_logout' %}" class="nav-link">
								<span class="{{ nav_actives.6 }}">
									<i class="fa fa-sign-out"></i> logout
								</span>
							</a>
						</li>
						{% else %}
						<li class="nav-item active">
							<a href="{% url 'account_login' %}" class="nav-link">
								<span class="{{ nav_actives.5 }}">
									<i class="fa fa-sign-in-alt"></i> Sign In
								</span>
							</a>
						</li>
						<li class="nav-item active">
							<a href="{% url 'account_signup' %}" class="nav-link">
								<span class="{{ nav_actives.6 }}">
									<i class="fa fa-user-plus"></i> Sign Up
								</span>
							</a>
						</li>
						{% endif %}
					</ul>
					
				</div>

			</nav>
		</div>
	</div>

	{% if user.is_authenticated %}
		{% if user.user_profile.theme == 'light' %}
			<div class="container">
				<div class="alert alert-info" role="alert">
					Dark mode is availble. checkout profile section to change theme.
				</div>
			</div>
		{% endif %}
	{% endif %}

	{% block msgs %}
		<div class="msg-container bg-light">
			<div class="container">
				{% if messages %}
					{% for msg in messages %}
						<div class="alert alert-{{ msg.tags }}" role="alert">
							{{ msg }}
							<button type="button" class="close" data-dismiss="alert" aria-label="close">
								<span aria-hidden="true">
									&times;
								</span>
							</button>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>

		<div class="toast" role="alert" aria-live="assertive" aria-atomic="true"
			data-delay="5000" data-animation="true" id="copied">
			<div class="toast-body bg-dark">
				<span id="toast-message">Link copied!</span>
				<button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	{% endblock %}

    {% block content%}
    {% endblock %}

    <footer id="footer" class="bg-light">
		<div class="container">
			<div class="group">

				<a href="https://www.instagram.com/input_and_print/" class="bg-secondary" target="_blank" title="input_and_print">
					<i class="fa fa-instagram"></i>
				</a>

				<a href="https://github.com/Ajay2810-hub" target="_blank" class="bg-secondary" title="Ajay2810-hub">
					<i class="fa fa-github"></i>
				</a>

				<a href="https://www.youtube.com/channel/UCR7jYPOu0Iun2z1Bdi_pTaQ" target="_blank" class="bg-secondary" title="Input And Print">
					<i class="fa fa-youtube"></i>
				</a>

			</div>

			<div class="foot">
				© 2020 Copyright -
				<a href="{% url 'base:home' %}" target="_blank">
					ebooksportal.herokuapp.com
				</a>
			</div>
		</div>
	</footer>


    <!-- FontAwesome -->
	<script src="https://kit.fontawesome.com/8065491d7c.js" crossorigin="anonymous"></script>

	<!-- BootStrap -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

	{% block scripts %}
	{% endblock %}
</body>
</html>